/********************************************************************
* nanoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error nanoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablenanoDict();
extern void G__cpp_setup_inheritancenanoDict();
extern void G__cpp_setup_typetablenanoDict();
extern void G__cpp_setup_memvarnanoDict();
extern void G__cpp_setup_globalnanoDict();
extern void G__cpp_setup_memfuncnanoDict();
extern void G__cpp_setup_funcnanoDict();
extern void G__set_cpp_environmentnanoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./src/AliJBaseTrack.h"
#include "./src/AliJBaseEventHeader.h"
#include "./src/JTreeDataManager.h"
#include "./src/JHistos.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__nanoDictLN_TClass;
extern G__linked_taginfo G__nanoDictLN_TBuffer;
extern G__linked_taginfo G__nanoDictLN_TMemberInspector;
extern G__linked_taginfo G__nanoDictLN_TObject;
extern G__linked_taginfo G__nanoDictLN_TNamed;
extern G__linked_taginfo G__nanoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__nanoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__nanoDictLN_TClonesArray;
extern G__linked_taginfo G__nanoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__nanoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__nanoDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__nanoDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__nanoDictLN_TLorentzVector;
extern G__linked_taginfo G__nanoDictLN_AliJBaseTrack;
extern G__linked_taginfo G__nanoDictLN_AliJBaseEventHeader;
extern G__linked_taginfo G__nanoDictLN_TH1D;
extern G__linked_taginfo G__nanoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__nanoDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__nanoDictLN_TChain;
extern G__linked_taginfo G__nanoDictLN_JTreeDataManager;
extern G__linked_taginfo G__nanoDictLN_JHistos;

/* STUB derived class for protected member access */
